swagger: '2.0'
info:
  title: Vulnerable API
  version: 0.0.1
schemes:
  - https
host: vulnerableapi.herokuapp.com  
basePath: /api
consumes:
  - application/json
produces:
  - application/json

paths:
  /pets:
    get:
      description: Returns all pets from the system that the user has access to
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - api_key: []
      responses:
        '200':
          description: A list of pets.
          schema:
            type: array
            items:
              $ref: '#/definitions/PetId'
  /pet:
    post:
      consumes:
        - application/json
        - application/xml
      security:
        - api_key: []
      parameters:
        - name: pet
          in: body
          required: true
          schema:
            $ref: '#/definitions/PetId'
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
  /pet/{pet_id}:
    put:
      consumes:
        - application/json
        - application/xml
      security:
        - api_key: []
      parameters:
        - name: pet_id
          in: path
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Pet'
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      
securityDefinitions:
  api_key:
    type: apiKey
    name: x-access-token
    in: header


definitions:
  Pet:
    required:
      - breed
      - name
      - tag
    type: object
    properties:
      breed:
        type: string
      name:
        type: string
      tag:
        type: string
  PetId:
    required:
      - id
      - breed
      - name
      - tag
    type: object
    properties:
      id:
        type: integer
        format: int64
      breed:
        type: string
      name:
        type: string
      tag:
        type: string
    
    

